version: "3.7"

services: 

  proxy:
    image: httpd
    container_name: apache
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
      #- ./html:/usr/local/apache2/htdocs
      #- ./conf:/usr/local/apache2/conf
      - httpdconf:/usr/local/apache2/conf
      - httpdhtml:/usr/local/apache2/htdocs  
    networks:
      - container
    dns:
      - 8.8.8.8
      - 1.1.1.1
  node:
    image: "node:19"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:app.js
    ports:
      - 3000:3000/tcp
    command: "npm start"

volumes:
  httpdconf:
  httpdhtml:

networks:
  container:
    driver: bridge
