FROM ubuntu:21.04

CMD ["bash"]
RUN apt-get update && apt-get install -y iputils-ping htop vim ca-certificates wget curl telnet mtr xz-utils
#COPY scripts /opt/scripts
#RUN cd /opt/scripts/ && ./build.sh