version: "3.7"

services: 

  proxy:
    image: httpd
    container_name: proxy
    restart: always
    ports:
    - 80:80
    volumes:
      #- ./html:/usr/local/apache2/htdocs
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - httpdconf:/usr/local/apache2/conf
      - httpdhtml:/usr/local/apache2/htdocs  
    networks:
      - container
    dns:
      - 8.8.8.8
      - 1.1.1.1
  node:
    image: "node:19"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app.js:/home/node/app/app.js
      - ./package.json:/home/node/app/package.json
    ports:
      - 3000:3000/tcp
    command: "npm start"
    networks:
      - container

volumes:
  httpdconf:
  httpdhtml:

networks:
  container:
    driver: bridge
