version: "3.7"

services: 

  proxy:
    image: httpd
    container_name: proxy
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/conf//httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ./certs/server.crt:/usr/local/apache2/conf/server.crt
      - ./certs/server.key:/usr/local/apache2/conf/server.key  
    networks:
      - container
    dns:
      - 8.8.8.8
      - 1.1.1.1
  node:
    image: "node:19"
    user: "node"
    working_dir: /opt/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./workdir/:/opt/node
    ports:
      - 3000:3000/tcp
    command: "npm start"
    networks:
      - container

volumes:
  httpdconf:
  httpdhtml:

networks:
  container:
    driver: bridge
