version: "3.7"

services: 

  proxy:
    image: httpd
    container_name: proxy
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
      - ${HTTPD_CONF}:/usr/local/apache2/conf/httpd.conf
      - ${HTTPD_SSL_CONF}:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ${SSL_CERT}:/usr/local/apache2/conf/server.crt
      - ${SSL_KEY}:/usr/local/apache2/conf/server.key  
    networks:
      - container
    dns:
      - ${DNS1}
      - ${DNS2}
  node:
    image: "node:19"
    user: ${NODE_USER}
    working_dir: ${WORKDIR}
    environment:
      - NODE_ENV=production
    volumes:
      - ./workdir/:${WORKDIR}
    ports:
      - 3000:3000/tcp
    command: /bin/bash -c "npm install && npm start"
    networks:
      - container

volumes:
  httpdconf:
  httpdhtml:

networks:
  container:
    driver: bridge
